services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-24.04

    # O comando "../..:/workspaces:cached" monta a árvore de arquivos local dentro do Dev Container
    volumes:
      - ../..:/workspaces:cached

    # O comando "sleep infinity" mantém o Container vivo até mandarmos ele parar
    command: sleep infinity
    depends_on:
      db:
        condition: service_healthy
  
  db:
    container_name: postgresql
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: gutguessr
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres-data: